CharlotteO9/ecocoach

app/controllers/application_controller.rb
app/models/booking.rb
app/models/challenge.rb
app/models/seniority.rb
app/models/tip.rb
app/models/user.rb
app/models/usertip.rb
db/migrate/20221128154715_create_seniorities.rb
db/migrate/20221128160210_add_column_to_users.rb
db/migrate/20221128161831_create_challenges.rb
db/migrate/20221128161941_create_tips.rb
db/migrate/20221128162212_create_bookings.rb
db/migrate/20221128162558_create_usertips.rb
db/schema.rb
test/models/booking_test.rb
test/models/challenge_test.rb
test/models/seniority_test.rb
test/models/tip_test.rb
test/models/usertip_test.rb

we created all the model but missing validations --> to do next

models are all ok

---

db/seeds.rb

complete the seed

---

config/routes.rb

The routes are set. 
Let us know if they seem fine to you

we have set the routes

---

Gemfile.lock
app/controllers/bookings_controller.rb
app/models/challenge.rb
app/models/user.rb
app/models/usertip.rb
test/controllers/bookings_controller_test.rb

correction des has many et belongs to (un par ligne)
creation du controller bookings vide

Controller booking

---

app/controllers/seniorities_controller.rb
test/controllers/seniorities_controller_test.rb

Seniorities controller + view
No def yet for the controller as we wait to see if we'll have time to make the seniorties selection at login later on

controller seniorities

---

app/controllers/bookings_controller.rb
db/schema.rb

j'ai créé les méthodes du controller bookings mais à vérifier avec la seed :)

methodes controller bookings

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/bookings/_form.html.erb
app/views/bookings/edit.html.erb
app/views/bookings/new.html.erb
app/views/bookings/show.html.erb
app/views/challenges/index.html.erb
app/views/challenges/show.html.erb

changement des validations (status & weeknumber) 
ajout des vues (show à réfléchir)

ajout des views bookings et correction validation

---

app/controllers/bookings_controller.rb
app/views/bookings/show.html.erb
app/views/pages/profile.html.erb

show new challenge ok - show on going challenge ok - show past challenge

show new challenge ok - show on going challenge ok - show past challenge

---

app/views/bookings/_form.html.erb
app/views/bookings/show.html.erb
db/schema.rb

modif du form booking, condition sur bouton + modif label

form booking avec conditions

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/challenges_controller.rb
app/controllers/pages_controller.rb
app/controllers/usertips_controller.rb
app/models/seniority.rb
app/policies/application_policy.rb
app/policies/booking_policy.rb
app/policies/challenge_policy.rb
app/policies/page_policy.rb
app/policies/pages_policy.rb
app/policies/seniority_policy.rb
app/policies/usertip_policy.rb
app/views/bookings/show.html.erb
app/views/pages/profile.html.erb
db/migrate/20221130131017_add_ranking_to_seniorities.rb
db/schema.rb
db/seeds.rb
test/policies/booking_policy_test.rb
test/policies/challenge_policy_test.rb
test/policies/pages_policy_test.rb
test/policies/seniority_policy_test.rb
test/policies/usertip_policy_test.rb

- added pundit
- added column ranking to seniority

Adding authorizations

---

app/controllers/bookings_controller.rb
app/controllers/challenges_controller.rb
app/controllers/saved_tips_controller.rb
app/controllers/saved_user_tips_controller.rb
app/models/saved_tip.rb
app/models/saved_user_tip.rb
app/models/user.rb
app/views/bookings/show.html.erb
app/views/challenges/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/migrate/20221130133306_create_saved_tips.rb
db/migrate/20221130133409_create_saved_user_tips.rb
db/schema.rb
test/controllers/savedtips_controller_test.rb
test/controllers/savedusertips_controller_test.rb
test/models/savedtip_test.rb
test/models/savedusertip_test.rb

ok pour save and unsave un tip d'un new challenge on going challenge et past challenge

Model saved (tips)

---

app/controllers/application_controller.rb
app/controllers/bookings_controller.rb

- changed path on evaluate the challenge to come back to profile
- changed booking controllerto redirect to profile at destroy
- added def in application controller to have a redirection to profile at sign-in

updating redirections

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Le front-end de la home page avec banner et carousel

second front home

---

app/controllers/pages_controller.rb
app/controllers/usertips_controller.rb
app/models/user.rb
app/views/pages/profile.html.erb
app/views/usertips/edit.html.erb

create and edit tips are working and tips created by user and saved by user are on profile

tips create / update / on profile

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_font.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_indexchallenges.scss
app/views/challenges/index.html.erb

added font components

---

app/assets/stylesheets/challenges/_index.scss
app/views/pages/profile_challenge.html.erb

le front des on going challenge et des passed challenges sur le profile

add front challenges

---

app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile_challenge.scss
app/views/bookings/show.html.erb
app/views/challenges/index.html.erb
app/views/challenges/show.html.erb
app/views/pages/profile_challenge.html.erb
app/views/pages/profile_tips.html.erb
app/views/pages/tipsindex.html.erb

tabs sur my challenge ok + modification des headers, il y a deux types

---

app/views/bookings/show.html.erb
app/views/pages/profile_tips.html.erb
app/views/pages/tipsindex.html.erb

quick fix on cards cf previous merge

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/seniorities/_index.scss
app/controllers/seniorities_controller.rb
app/helpers/icons_helper.rb
app/policies/seniority_policy.rb
app/views/seniorities/index.html.erb
config/routes.rb
db/migrate/20221205135240_add_description_to_seniorities.rb
db/schema.rb
db/seeds.rb

seniorities

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/controllers/pages_controller.rb
app/views/pages/profile.html.erb
app/views/pages/profile_challenge.html.erb

profil amélioré mais pas terminé

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_container_nav.scss
app/assets/stylesheets/components/_navbar_eco.scss
app/assets/stylesheets/pages/_form_eco.scss
app/javascript/controllers/index.js
app/views/bookings/_form.html.erb
app/views/pages/profile_tips.html.erb
db/schema.rb

Sur My tips, 
- changement des tabs en accordéons comme sur challenge
- reprise du visu my challenges pour l'appliquer a my tips
- les boutons sont en bas il faut que j'arrive à les centrer mais qqch bloque :(

accordeon and buttons bottom on my tips

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_form_eco.scss
app/assets/stylesheets/pages/_profile_challenge.scss
app/javascript/controllers/search_tips_controller.js
app/views/bookings/show.html.erb
app/views/pages/profile_challenge.html.erb
app/views/pages/tipsindex.html.erb

j'ai remis pas mal de boutons en bas de page
search fonctionnelle !!!! et belllllle

boutons en bas et search ok

---

app/assets/stylesheets/challenges/_show.scss
app/assets/stylesheets/components/_cardtips.scss
app/views/bookings/show.html.erb
app/views/challenges/show.html.erb

continue show

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_challenges_show.scss
app/assets/stylesheets/pages/_form_eco.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/views/bookings/_form.html.erb
app/views/bookings/show.html.erb
app/views/challenges/show.html.erb
app/views/pages/profile_tips.html.erb

changement sur les boutons, encore celui avec "réussi" à changer demain, il faut encore réfléchir à une idée cool

buttons front

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/controllers/events_controller.rb
app/views/events/index.html.erb
db/schema.rb

Added gem simple_calendar + displayed it on the view

added simple calendar gem

---

db/migrate/20221207092202_add_url_to_events.rb
db/schema.rb

add url to events

---

app/assets/stylesheets/components/_event.scss
app/assets/stylesheets/components/_index.scss
app/views/events/index.html.erb

Première couche de front pour la page events

first styling event page

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/config/_colors.scss
app/javascript/controllers/booking_goal_controller.js
app/views/bookings/_form.html.erb

J'ai modifié le texte du goal pour mettre "set your weekly goal" sinon ca faisait 2 lignes (meme en réduisant la police) et c'était pas beau... ok pour vous ?
j'ai commencé le travail sur agrandir les tailles de police dans la search, j'ai encore besoin de temps demain pour aligner les categories au c
entre :)

text goal et buttons category search

---

app/assets/stylesheets/challenges/_show.scss
app/assets/stylesheets/components/_card_challenge.scss
app/assets/stylesheets/components/_container_nav.scss
app/assets/stylesheets/components/_header.scss
app/views/pages/profile_challenge.html.erb

put-medals

---

app/assets/stylesheets/seniorities/_index.scss
app/views/seniorities/index.html.erb
db/seeds.rb

Polish on seniorities/level page as per feedback from demo
- added back to profile button
- replaced profile with ranking icon
- page title not aligned yet with icon as done by will on the global css for all pages
-

polished seniorities

---

app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/_navbar_eco.scss
app/views/bookings/show.html.erb
app/views/pages/profile_challenge.html.erb
app/views/shared/_navbar_eco.html.erb

Navbar update

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_form_eco.scss
app/views/bookings/_form.html.erb
app/views/pages/profile_tips.html.erb
app/views/pages/tipsindex.html.erb

boutons mis à jour selon les retours de la dress session :)

buttons ok suite retours

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_form_eco.scss
app/views/bookings/_form.html.erb
app/views/pages/profile_tips.html.erb
app/views/pages/tipsindex.html.erb

bouton goal maj pour etre au dessus de add this challenge

Button goal

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_button.scss
app/views/events/index.html.erb
app/views/pages/_modal.html.erb
app/views/pages/_modal_edit.html.erb
app/views/pages/profile_challenge.html.erb
public/404.html
public/500.html

Fix texte bouton des deux modal (Post your tip / Update your tip)
Fix accordeon pour que chacun s'ouvre et se ferme indépendamment
Fix events, il n'y a plus le probleme en bas (du a un = en trop sur each do)

buttons + accordeon

---

app/assets/stylesheets/pages/_booking_show.scss
app/assets/stylesheets/pages/_challenges_show.scss
app/assets/stylesheets/pages/_index.scss

ok pour aplat, peut etre essayer de blur demain

 ok pour aplat

---

app/assets/stylesheets/components/_button.scss
db/seeds.rb

add this challenge bleu --> fix
petite fleche on going challenge et passed challenge bleu --> fix 
? pour you want change your habits --> fix

fix last things

---

app/assets/stylesheets/components/_button.scss
db/schema.rb

button home white

---

app/views/pages/_modal.html.erb
app/views/pages/_modal_edit.html.erb

j'ai changé le texte de "Name" pour "Title"

change text modals
